version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: uniadpativelti-back
    container_name: uniadpativelti-back
    restart: unless-stopped
    tty: true
    ports:
      - 9000:9000
    environment:
      APP_NAME: UNIAdaptiveLTI-BackEnd
      ETC:
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - uniadaptive-network
networks:
  uniadaptive-network:
    driver: bridge
